### ISSUE TITLE
RE: Takeover

### ISSUE THREAD

**Issue by VerHext** [hackbros1337/SupportPP#1]
As the domain owner of the domain `support-pp.de`, I find it interesting that you take over an unused subdomain with a GitHub CNAME record.
Personally, I think it would be better if you had told us about the issue, for example via e-mail.
We only found out that the domain was in use via an SSL renewal notification. Since the adoption of a subdomain brings serious security flaws such as CORS problems. We have removed the DNS record.

We therefore ask you to delete the now redundant repository or its CNAME reference.

**Comment by hackbros1337** [comment]
I had tried contacting via email on 2nd October, 2020.
No one replied though.
Anyways, deleting the repo.
Thank you for the reply!
